<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122213209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE prerequis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, responsable VARCHAR(100) DEFAULT NULL, date_cible DATE DEFAULT NULL, statut VARCHAR(20) NOT NULL, ordre INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campagne_id INT NOT NULL, segment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CAE3EB0916227374 ON prerequis (campagne_id)');
        $this->addSql('CREATE INDEX IDX_CAE3EB09DB296AAD ON prerequis (segment_id)');
        $this->addSql('ALTER TABLE prerequis ADD CONSTRAINT FK_CAE3EB0916227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prerequis ADD CONSTRAINT FK_CAE3EB09DB296AAD FOREIGN KEY (segment_id) REFERENCES segment (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE prerequis DROP CONSTRAINT FK_CAE3EB0916227374');
        $this->addSql('ALTER TABLE prerequis DROP CONSTRAINT FK_CAE3EB09DB296AAD');
        $this->addSql('DROP TABLE prerequis');
    }
}
