<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122062156 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Sprint 2 - Core data model: Campagne, TypeOperation, Segment, Operation, ChecklistTemplate, ChecklistInstance';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campagne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, proprietaire_id INT DEFAULT NULL, type_operation_id INT DEFAULT NULL, checklist_template_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_539B5D166C6E55B5 ON campagne (nom)');
        $this->addSql('CREATE INDEX IDX_539B5D1676C50E4A ON campagne (proprietaire_id)');
        $this->addSql('CREATE INDEX IDX_539B5D16C3EF8F86 ON campagne (type_operation_id)');
        $this->addSql('CREATE INDEX IDX_539B5D161316BF28 ON campagne (checklist_template_id)');
        $this->addSql('CREATE TABLE checklist_instance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, template_version INT NOT NULL, snapshot JSON NOT NULL, progression JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, template_id INT DEFAULT NULL, operation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F34CD1C5DA0FB8 ON checklist_instance (template_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F34CD1C44AC3583 ON checklist_instance (operation_id)');
        $this->addSql('CREATE TABLE checklist_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, version INT NOT NULL, etapes JSON NOT NULL, actif BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, matricule VARCHAR(50) NOT NULL, nom VARCHAR(255) NOT NULL, statut VARCHAR(20) NOT NULL, donnees_personnalisees JSONB DEFAULT NULL, motif_report TEXT DEFAULT NULL, notes TEXT DEFAULT NULL, date_planifiee DATE DEFAULT NULL, date_realisation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campagne_id INT NOT NULL, segment_id INT DEFAULT NULL, type_operation_id INT DEFAULT NULL, technicien_assigne_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1981A66D16227374 ON operation (campagne_id)');
        $this->addSql('CREATE INDEX IDX_1981A66DDB296AAD ON operation (segment_id)');
        $this->addSql('CREATE INDEX IDX_1981A66DC3EF8F86 ON operation (type_operation_id)');
        $this->addSql('CREATE INDEX IDX_1981A66DB4C58F73 ON operation (technicien_assigne_id)');
        $this->addSql('CREATE INDEX idx_operation_statut ON operation (statut)');
        $this->addSql('CREATE INDEX idx_operation_matricule ON operation (matricule)');
        $this->addSql('CREATE TABLE segment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, couleur VARCHAR(20) NOT NULL, ordre INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campagne_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1881F56516227374 ON segment (campagne_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_segment_nom_campagne ON segment (nom, campagne_id)');
        $this->addSql('CREATE TABLE type_operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, icone VARCHAR(50) NOT NULL, couleur VARCHAR(20) NOT NULL, champs_personnalises JSON DEFAULT NULL, actif BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD47E77D6C6E55B5 ON type_operation (nom)');
        $this->addSql('ALTER TABLE campagne ADD CONSTRAINT FK_539B5D1676C50E4A FOREIGN KEY (proprietaire_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campagne ADD CONSTRAINT FK_539B5D16C3EF8F86 FOREIGN KEY (type_operation_id) REFERENCES type_operation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campagne ADD CONSTRAINT FK_539B5D161316BF28 FOREIGN KEY (checklist_template_id) REFERENCES checklist_template (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE checklist_instance ADD CONSTRAINT FK_1F34CD1C5DA0FB8 FOREIGN KEY (template_id) REFERENCES checklist_template (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE checklist_instance ADD CONSTRAINT FK_1F34CD1C44AC3583 FOREIGN KEY (operation_id) REFERENCES operation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66D16227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DDB296AAD FOREIGN KEY (segment_id) REFERENCES segment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DC3EF8F86 FOREIGN KEY (type_operation_id) REFERENCES type_operation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE operation ADD CONSTRAINT FK_1981A66DB4C58F73 FOREIGN KEY (technicien_assigne_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE segment ADD CONSTRAINT FK_1881F56516227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE campagne DROP CONSTRAINT FK_539B5D1676C50E4A');
        $this->addSql('ALTER TABLE campagne DROP CONSTRAINT FK_539B5D16C3EF8F86');
        $this->addSql('ALTER TABLE campagne DROP CONSTRAINT FK_539B5D161316BF28');
        $this->addSql('ALTER TABLE checklist_instance DROP CONSTRAINT FK_1F34CD1C5DA0FB8');
        $this->addSql('ALTER TABLE checklist_instance DROP CONSTRAINT FK_1F34CD1C44AC3583');
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66D16227374');
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66DDB296AAD');
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66DC3EF8F86');
        $this->addSql('ALTER TABLE operation DROP CONSTRAINT FK_1981A66DB4C58F73');
        $this->addSql('ALTER TABLE segment DROP CONSTRAINT FK_1881F56516227374');
        $this->addSql('DROP TABLE campagne');
        $this->addSql('DROP TABLE checklist_instance');
        $this->addSql('DROP TABLE checklist_template');
        $this->addSql('DROP TABLE operation');
        $this->addSql('DROP TABLE segment');
        $this->addSql('DROP TABLE type_operation');
    }
}
