<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122210923 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_campagne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_8735288187d069e53721b1766d30b1d0_idx ON audit_campagne (type)');
        $this->addSql('CREATE INDEX object_id_8735288187d069e53721b1766d30b1d0_idx ON audit_campagne (object_id)');
        $this->addSql('CREATE INDEX discriminator_8735288187d069e53721b1766d30b1d0_idx ON audit_campagne (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_8735288187d069e53721b1766d30b1d0_idx ON audit_campagne (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_8735288187d069e53721b1766d30b1d0_idx ON audit_campagne (blame_id)');
        $this->addSql('CREATE INDEX created_at_8735288187d069e53721b1766d30b1d0_idx ON audit_campagne (created_at)');
        $this->addSql('CREATE TABLE audit_checklist_instance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_be53e9a3ecdc1fcff9eff019550de345_idx ON audit_checklist_instance (type)');
        $this->addSql('CREATE INDEX object_id_be53e9a3ecdc1fcff9eff019550de345_idx ON audit_checklist_instance (object_id)');
        $this->addSql('CREATE INDEX discriminator_be53e9a3ecdc1fcff9eff019550de345_idx ON audit_checklist_instance (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_be53e9a3ecdc1fcff9eff019550de345_idx ON audit_checklist_instance (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_be53e9a3ecdc1fcff9eff019550de345_idx ON audit_checklist_instance (blame_id)');
        $this->addSql('CREATE INDEX created_at_be53e9a3ecdc1fcff9eff019550de345_idx ON audit_checklist_instance (created_at)');
        $this->addSql('CREATE TABLE audit_checklist_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_2e8ededaafdc0abe107287b69f92737a_idx ON audit_checklist_template (type)');
        $this->addSql('CREATE INDEX object_id_2e8ededaafdc0abe107287b69f92737a_idx ON audit_checklist_template (object_id)');
        $this->addSql('CREATE INDEX discriminator_2e8ededaafdc0abe107287b69f92737a_idx ON audit_checklist_template (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_2e8ededaafdc0abe107287b69f92737a_idx ON audit_checklist_template (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_2e8ededaafdc0abe107287b69f92737a_idx ON audit_checklist_template (blame_id)');
        $this->addSql('CREATE INDEX created_at_2e8ededaafdc0abe107287b69f92737a_idx ON audit_checklist_template (created_at)');
        $this->addSql('CREATE TABLE audit_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_ab14d13cc30afb36583962e36e3967d4_idx ON audit_document (type)');
        $this->addSql('CREATE INDEX object_id_ab14d13cc30afb36583962e36e3967d4_idx ON audit_document (object_id)');
        $this->addSql('CREATE INDEX discriminator_ab14d13cc30afb36583962e36e3967d4_idx ON audit_document (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_ab14d13cc30afb36583962e36e3967d4_idx ON audit_document (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_ab14d13cc30afb36583962e36e3967d4_idx ON audit_document (blame_id)');
        $this->addSql('CREATE INDEX created_at_ab14d13cc30afb36583962e36e3967d4_idx ON audit_document (created_at)');
        $this->addSql('CREATE TABLE audit_operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_433aeb55d49a2f0c1c46b8888e522d47_idx ON audit_operation (type)');
        $this->addSql('CREATE INDEX object_id_433aeb55d49a2f0c1c46b8888e522d47_idx ON audit_operation (object_id)');
        $this->addSql('CREATE INDEX discriminator_433aeb55d49a2f0c1c46b8888e522d47_idx ON audit_operation (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_433aeb55d49a2f0c1c46b8888e522d47_idx ON audit_operation (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_433aeb55d49a2f0c1c46b8888e522d47_idx ON audit_operation (blame_id)');
        $this->addSql('CREATE INDEX created_at_433aeb55d49a2f0c1c46b8888e522d47_idx ON audit_operation (created_at)');
        $this->addSql('CREATE TABLE audit_segment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_3a6207256dfeb6b0a0476c2ab1f8f010_idx ON audit_segment (type)');
        $this->addSql('CREATE INDEX object_id_3a6207256dfeb6b0a0476c2ab1f8f010_idx ON audit_segment (object_id)');
        $this->addSql('CREATE INDEX discriminator_3a6207256dfeb6b0a0476c2ab1f8f010_idx ON audit_segment (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_3a6207256dfeb6b0a0476c2ab1f8f010_idx ON audit_segment (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_3a6207256dfeb6b0a0476c2ab1f8f010_idx ON audit_segment (blame_id)');
        $this->addSql('CREATE INDEX created_at_3a6207256dfeb6b0a0476c2ab1f8f010_idx ON audit_segment (created_at)');
        $this->addSql('CREATE TABLE audit_type_operation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_644b09d522b5ccd56cdbeae6a87c0cd3_idx ON audit_type_operation (type)');
        $this->addSql('CREATE INDEX object_id_644b09d522b5ccd56cdbeae6a87c0cd3_idx ON audit_type_operation (object_id)');
        $this->addSql('CREATE INDEX discriminator_644b09d522b5ccd56cdbeae6a87c0cd3_idx ON audit_type_operation (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_644b09d522b5ccd56cdbeae6a87c0cd3_idx ON audit_type_operation (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_644b09d522b5ccd56cdbeae6a87c0cd3_idx ON audit_type_operation (blame_id)');
        $this->addSql('CREATE INDEX created_at_644b09d522b5ccd56cdbeae6a87c0cd3_idx ON audit_type_operation (created_at)');
        $this->addSql('CREATE TABLE audit_utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_9060c12c3386a6040825143ca21e63f2_idx ON audit_utilisateur (type)');
        $this->addSql('CREATE INDEX object_id_9060c12c3386a6040825143ca21e63f2_idx ON audit_utilisateur (object_id)');
        $this->addSql('CREATE INDEX discriminator_9060c12c3386a6040825143ca21e63f2_idx ON audit_utilisateur (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_9060c12c3386a6040825143ca21e63f2_idx ON audit_utilisateur (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_9060c12c3386a6040825143ca21e63f2_idx ON audit_utilisateur (blame_id)');
        $this->addSql('CREATE INDEX created_at_9060c12c3386a6040825143ca21e63f2_idx ON audit_utilisateur (created_at)');
        $this->addSql('ALTER TABLE campagne ALTER visibilite DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE audit_campagne');
        $this->addSql('DROP TABLE audit_checklist_instance');
        $this->addSql('DROP TABLE audit_checklist_template');
        $this->addSql('DROP TABLE audit_document');
        $this->addSql('DROP TABLE audit_operation');
        $this->addSql('DROP TABLE audit_segment');
        $this->addSql('DROP TABLE audit_type_operation');
        $this->addSql('DROP TABLE audit_utilisateur');
        $this->addSql('ALTER TABLE campagne ALTER visibilite SET DEFAULT \'restreinte\'');
    }
}
