<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260129221149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent ALTER sms_opt_in DROP DEFAULT');
        $this->addSql('ALTER INDEX uniq_268b9c9d5f37a13b RENAME TO UNIQ_268B9C9DCE4B5C8E');
        $this->addSql('ALTER TABLE campagne ADD checklist_mapping JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE campagne ALTER jours_verrouillage DROP DEFAULT');
        $this->addSql('ALTER TABLE checklist_instance ALTER etapes_cochees DROP DEFAULT');
        $this->addSql('ALTER TABLE checklist_instance ALTER etapes_cochees SET NOT NULL');
        $this->addSql('ALTER TABLE coordinateur_perimetre ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE coordinateur_perimetre ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN coordinateur_perimetre.created_at IS \'\'');
        $this->addSql('ALTER INDEX idx_coord_perimetre_coordinateur RENAME TO IDX_2F1BD982D32E46EA');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent ALTER sms_opt_in SET DEFAULT false');
        $this->addSql('ALTER INDEX uniq_268b9c9dce4b5c8e RENAME TO uniq_268b9c9d5f37a13b');
        $this->addSql('ALTER TABLE campagne DROP checklist_mapping');
        $this->addSql('ALTER TABLE campagne ALTER jours_verrouillage SET DEFAULT 2');
        $this->addSql('ALTER TABLE checklist_instance ALTER etapes_cochees SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE checklist_instance ALTER etapes_cochees DROP NOT NULL');
        $this->addSql('ALTER TABLE coordinateur_perimetre ALTER id SET DEFAULT nextval(\'coordinateur_perimetre_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE coordinateur_perimetre ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN coordinateur_perimetre.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER INDEX idx_2f1bd982d32e46ea RENAME TO idx_coord_perimetre_coordinateur');
    }
}
