<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122211957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE habilitation_campagne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, peut_voir BOOLEAN NOT NULL, peut_positionner BOOLEAN NOT NULL, peut_configurer BOOLEAN NOT NULL, peut_exporter BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campagne_id INT NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8A9F540716227374 ON habilitation_campagne (campagne_id)');
        $this->addSql('CREATE INDEX IDX_8A9F5407FB88E14F ON habilitation_campagne (utilisateur_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_habilitation ON habilitation_campagne (campagne_id, utilisateur_id)');
        $this->addSql('ALTER TABLE habilitation_campagne ADD CONSTRAINT FK_8A9F540716227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE habilitation_campagne ADD CONSTRAINT FK_8A9F5407FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE habilitation_campagne DROP CONSTRAINT FK_8A9F540716227374');
        $this->addSql('ALTER TABLE habilitation_campagne DROP CONSTRAINT FK_8A9F5407FB88E14F');
        $this->addSql('DROP TABLE habilitation_campagne');
    }
}
