<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajout table campagne_champ pour gestion manuelle des colonnes campagne.
 */
final class Version20260129200141 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout table campagne_champ pour gestion manuelle des colonnes campagne';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE campagne_champ (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, ordre INT DEFAULT NULL, campagne_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B4EE108116227374 ON campagne_champ (campagne_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_champ_nom_campagne ON campagne_champ (nom, campagne_id)');
        $this->addSql('ALTER TABLE campagne_champ ADD CONSTRAINT FK_B4EE108116227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE campagne_champ DROP CONSTRAINT FK_B4EE108116227374');
        $this->addSql('DROP TABLE campagne_champ');
    }
}
