<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260131180923 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add 3 reservation modes: libre, import (CampagneAgentAutorise), annuaire (Agent filters)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campagne_agent_autorise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identifiant VARCHAR(255) NOT NULL, nom_prenom VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, service VARCHAR(100) DEFAULT NULL, site VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, campagne_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5798082316227374 ON campagne_agent_autorise (campagne_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5798082316227374C90409EC ON campagne_agent_autorise (campagne_id, identifiant)');
        $this->addSql('ALTER TABLE campagne_agent_autorise ADD CONSTRAINT FK_5798082316227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE agent ADD role VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE agent ADD type_contrat VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE campagne ADD reservation_filtres_annuaire JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE campagne_agent_autorise DROP CONSTRAINT FK_5798082316227374');
        $this->addSql('DROP TABLE campagne_agent_autorise');
        $this->addSql('ALTER TABLE agent DROP role');
        $this->addSql('ALTER TABLE agent DROP type_contrat');
        $this->addSql('ALTER TABLE campagne DROP reservation_filtres_annuaire');
    }
}
