<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260122203612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_fichier VARCHAR(255) NOT NULL, nom_original VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, taille INT NOT NULL, extension VARCHAR(10) NOT NULL, type VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campagne_id INT NOT NULL, uploade_par_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A766E8D3472 ON document (uploade_par_id)');
        $this->addSql('CREATE INDEX idx_document_campagne ON document (campagne_id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7616227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A766E8D3472 FOREIGN KEY (uploade_par_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7616227374');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A766E8D3472');
        $this->addSql('DROP TABLE document');
    }
}
