<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260124130004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, matricule VARCHAR(50) NOT NULL, email VARCHAR(180) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, service VARCHAR(100) DEFAULT NULL, site VARCHAR(100) DEFAULT NULL, actif BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, manager_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_268B9C9D12B2DC9C ON agent (matricule)');
        $this->addSql('CREATE INDEX IDX_268B9C9D783E3463 ON agent (manager_id)');
        $this->addSql('CREATE TABLE creneau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, heure_debut TIME(0) WITHOUT TIME ZONE NOT NULL, heure_fin TIME(0) WITHOUT TIME ZONE NOT NULL, capacite INT NOT NULL, lieu VARCHAR(255) DEFAULT NULL, verrouille BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, campagne_id INT NOT NULL, segment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9668B5F16227374 ON creneau (campagne_id)');
        $this->addSql('CREATE INDEX IDX_F9668B5FDB296AAD ON creneau (segment_id)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, sujet VARCHAR(255) NOT NULL, contenu TEXT NOT NULL, statut VARCHAR(20) NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, agent_id INT NOT NULL, reservation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA3414710B ON notification (agent_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAB83297E7 ON notification (reservation_id)');
        $this->addSql('CREATE TABLE reservation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_positionnement VARCHAR(20) NOT NULL, statut VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, agent_id INT NOT NULL, creneau_id INT NOT NULL, campagne_id INT NOT NULL, positionne_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42C849553414710B ON reservation (agent_id)');
        $this->addSql('CREATE INDEX IDX_42C849557D0729A9 ON reservation (creneau_id)');
        $this->addSql('CREATE INDEX IDX_42C8495516227374 ON reservation (campagne_id)');
        $this->addSql('CREATE INDEX IDX_42C84955C29F49C7 ON reservation (positionne_par_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_agent_campagne ON reservation (agent_id, campagne_id)');
        $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9D783E3463 FOREIGN KEY (manager_id) REFERENCES agent (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE creneau ADD CONSTRAINT FK_F9668B5F16227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE creneau ADD CONSTRAINT FK_F9668B5FDB296AAD FOREIGN KEY (segment_id) REFERENCES segment (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA3414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAB83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849553414710B FOREIGN KEY (agent_id) REFERENCES agent (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C849557D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495516227374 FOREIGN KEY (campagne_id) REFERENCES campagne (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955C29F49C7 FOREIGN KEY (positionne_par_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agent DROP CONSTRAINT FK_268B9C9D783E3463');
        $this->addSql('ALTER TABLE creneau DROP CONSTRAINT FK_F9668B5F16227374');
        $this->addSql('ALTER TABLE creneau DROP CONSTRAINT FK_F9668B5FDB296AAD');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA3414710B');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAB83297E7');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849553414710B');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C849557D0729A9');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C8495516227374');
        $this->addSql('ALTER TABLE reservation DROP CONSTRAINT FK_42C84955C29F49C7');
        $this->addSql('DROP TABLE agent');
        $this->addSql('DROP TABLE creneau');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE reservation');
    }
}
